SET IDENTITY_INSERT Role ON
INSERT INTO Role (id, role)
SELECT 1, 'Admin'
UNION ALL SELECT 2, 'User'
SET IDENTITY_INSERT Role OFF

SET IDENTITY_INSERT Content ON
INSERT INTO Content (id, content)
SELECT
1,'Home'
UNION ALL SELECT
2,'HowToPlay'
UNION ALL SELECT
3,'LeaderBoard'
UNION ALL SELECT
4,'Legends'
UNION ALL SELECT
5,'Login'
UNION ALL SELECT
6,'Register'
UNION ALL SELECT
7,'Profile'
UNION ALL SELECT
8,'Score'
UNION ALL SELECT
9,'Bracket'
UNION ALL SELECT
10,'Winners'
UNION ALL SELECT
11,'Matchups'
UNION ALL SELECT
12,'Teams'
UNION ALL SELECT
13,'Users'
UNION ALL SELECT
14,'Play'
UNION ALL SELECT
15,'AdminHome'
UNION ALL SELECT
16,'TournyEntry'
UNION ALL SELECT
17,'Regions'
UNION ALL SELECT
18,'GenTourny'
UNION ALL SELECT
19,'GenMatchup'
UNION ALL SELECT
20,'PickWinner'
UNION ALL SELECT
21,'UserPanel'
UNION ALL SELECT
22,'MimicPlay'
UNION ALL SELECT
23,'ActivateUser'
UNION ALL SELECT
24,'ChangeUserPass'
UNION ALL SELECT
25,'Role'
SET IDENTITY_INSERT Content OFF

INSERT INTO [Rank] ([rank])
SELECT 1
UNION ALL SELECT 2
UNION ALL SELECT 3
UNION ALL SELECT 4
UNION ALL SELECT 5
UNION ALL SELECT 6
UNION ALL SELECT 7
UNION ALL SELECT 8
UNION ALL SELECT 9
UNION ALL SELECT 10
UNION ALL SELECT 11
UNION ALL SELECT 12
UNION ALL SELECT 13
UNION ALL SELECT 14
UNION ALL SELECT 15
UNION ALL SELECT 16

INSERT INTO [Round] (roundNo)
SELECT 1
UNION ALL SELECT 2
UNION ALL SELECT 3
UNION ALL SELECT 4
UNION ALL SELECT 5
UNION ALL SELECT 6

INSERT INTO RoleContent (roleID, contentID)
SELECT
1,1
UNION ALL SELECT
1,2
UNION ALL SELECT
1,3
UNION ALL SELECT
1,4
UNION ALL SELECT
1,5
UNION ALL SELECT
1,6
UNION ALL SELECT
1,7
UNION ALL SELECT
1,8
UNION ALL SELECT
1,9
UNION ALL SELECT
1,10
UNION ALL SELECT
1,11
UNION ALL SELECT
1,12
UNION ALL SELECT
1,13
UNION ALL SELECT
1,14
UNION ALL SELECT
1,15
UNION ALL SELECT
1,16
UNION ALL SELECT
1,17
UNION ALL SELECT
1,18
UNION ALL SELECT
1,19
UNION ALL SELECT
1,20
UNION ALL SELECT
1,21
UNION ALL SELECT
1,22
UNION ALL SELECT
1,23
UNION ALL SELECT
1,24
UNION ALL SELECT
1,25
UNION ALL SELECT
2,1
UNION ALL SELECT
2,2
UNION ALL SELECT
2,3
UNION ALL SELECT
2,4
UNION ALL SELECT
2,5
UNION ALL SELECT
2,6
UNION ALL SELECT
2,7
UNION ALL SELECT
2,14